import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { RunRecord } from "./types.js";
import { ensureDir, exists, redact } from "./utils.js";

export async function saveRecord(runDir: string, record: RunRecord) {
  await ensureDir(runDir);
  record.finishedAt = new Date().toISOString();
  const safe = sanitizeRecord(record);
  await writeFile(join(runDir, "run.json"), JSON.stringify(safe, null, 2));
  await writeFile(join(runDir, "report.html"), renderReport(safe));
}
function sanitizeRecord(record: RunRecord): RunRecord {
  return {
    ...record,
    baseUrl: redact(record.baseUrl),
    checks: record.checks.map((check) => ({ ...check, detail: redact(check.detail) })),
    visuals: record.visuals.map((visual) => ({ ...visual, route: redact(visual.route), ariaDiffText: visual.ariaDiffText === undefined ? undefined : redact(visual.ariaDiffText) })),
    configSummary: record.configSummary ? { ...record.configSummary, routes: record.configSummary.routes.map(redact) } : undefined,
  };
}
export async function loadRecord(runDir: string): Promise<RunRecord> {
  const path = join(runDir, "run.json");
  if (!(await exists(path))) throw new Error(`No run record found: ${path}`);
  return JSON.parse(await readFile(path, "utf8")) as RunRecord;
}
export function renderReport(run: RunRecord) {
  const passed = run.checks.filter((item) => item.status === "passed").length + run.visuals.filter((item) => item.status === "passed").length;
  const failed = run.checks.filter((item) => item.status === "failed").length + run.visuals.filter((item) => item.status === "failed").length;
  const cards = run.visuals.map((item) => `<article class="visual ${item.status}"><header><strong>${esc(item.route)} · ${esc(item.viewport)}</strong><span>${(item.diffPixelRatio * 100).toFixed(3)}%${item.ariaStatus ? ` · <span class="aria-badge ${item.ariaStatus}">ARIA ${item.ariaStatus}</span>` : ""}</span></header><div class="shots"><figure><img src="${attr(item.baseline)}" alt="Baseline"><figcaption>Baseline</figcaption></figure><figure><img src="${attr(item.current)}" alt="Current"><figcaption>Current</figcaption></figure><figure><img src="${attr(item.diff)}" alt="Diff"><figcaption>Diff</figcaption></figure></div>${item.ariaDiffText ? `<details class="aria-diff"><summary>ARIA snapshot diff</summary><pre>${esc(item.ariaDiffText)}</pre>${item.ariaDiff ? `<p><a href="${attr(item.ariaDiff)}">${esc(item.ariaDiff)}</a></p>` : ""}</details>` : ""}</article>`).join("");
  const checks = run.checks.map((item) => `<tr><td><span class="dot ${item.status}"></span>${esc(item.name)}</td><td>${esc(item.status)}</td><td>${esc(item.detail)}</td></tr>`).join("");
  const stages = (run.stages ?? []).map((stage) => `<tr><td>${esc(stage.name)}</td><td>${esc(stage.status)}</td><td>${esc(stage.startedAt)}</td><td>${esc(stage.finishedAt || "")}</td></tr>`).join("");
  const config = run.configSummary;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Frontend Promotion Guard report</title><style>${styles}</style></head><body><main><p class="eyebrow">FRONTEND PROMOTION GUARD</p><h1>Release acceptance report</h1><p class="lede">Static evidence for build semantics, computed styles, screenshots, promotion, and rollback.</p><section class="summary"><div><small>Result</small><strong class="${failed ? "bad" : "good"}">${failed ? "FAILED" : "PASSED"}</strong></div><div><small>Checks</small><strong>${passed} passed · ${failed} failed</strong></div><div><small>Final state</small><strong>${esc(run.finalState || "verification only")}</strong></div><div><small>Command</small><strong>${esc(run.command)}</strong></div></section><section><h2>Release identity</h2><dl><dt>Commit</dt><dd>${esc(run.commit || "unknown")}</dd><dt>Base URL</dt><dd>${esc(run.baseUrl)}</dd><dt>Candidate reference</dt><dd>${esc(run.candidateImage || "n/a")}</dd><dt>Candidate image ID</dt><dd>${esc(run.candidateImageId || "n/a")}</dd><dt>Production reference</dt><dd>${esc(run.productionImage || "n/a")}</dd><dt>Previous production ID</dt><dd>${esc(run.previousProductionImageId || "n/a")}</dd><dt>Final production ID</dt><dd>${esc(run.finalProductionImageId || "n/a")}</dd><dt>Rollback reference</dt><dd>${esc(run.rollbackImage || "n/a")}</dd><dt>Rolled back</dt><dd>${run.rolledBack ? "yes" : "no"}</dd><dt>Platform</dt><dd>${esc(run.environment?.platform || "unknown")}</dd><dt>Node.js</dt><dd>${esc(run.environment?.node || "unknown")}</dd><dt>Browser</dt><dd>${esc(run.environment?.browser || "n/a")}</dd><dt>Started</dt><dd>${esc(run.startedAt)}</dd><dt>Finished</dt><dd>${esc(run.finishedAt || "")}</dd></dl></section><section><h2>Configuration summary</h2><dl><dt>Routes</dt><dd>${esc(config?.routes.join(", ") || "n/a")}</dd><dt>Viewports</dt><dd>${esc(config?.viewports.join(", ") || "n/a")}</dd><dt>Maximum diff ratio</dt><dd>${config?.maxDiffPixelRatio ?? "n/a"}</dd><dt>Pixel threshold</dt><dd>${config?.pixelThreshold ?? "n/a"}</dd></dl></section>${stages ? `<section><h2>Release stages</h2><div class="table"><table><thead><tr><th>Stage</th><th>Status</th><th>Started</th><th>Finished</th></tr></thead><tbody>${stages}</tbody></table></div></section>` : ""}<section><h2>Test results</h2><div class="table"><table><thead><tr><th>Check</th><th>Status</th><th>Detail</th></tr></thead><tbody>${checks}</tbody></table></div></section><section><h2>Visual evidence</h2><div class="visuals">${cards || "<p>No visual evidence recorded.</p>"}</div></section></main></body></html>`;
}
const esc = (value: string) => value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);
const attr = esc;
const styles = `:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#1c1917;background:#f5f5f4}*{box-sizing:border-box}body{margin:0}main{width:min(1180px,calc(100% - 40px));margin:64px auto}.eyebrow{font-size:12px;font-weight:700;letter-spacing:.16em;color:#78716c}h1{font-size:clamp(34px,5vw,58px);letter-spacing:-.045em;margin:10px 0}.lede{font-size:18px;color:#57534e;max-width:680px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:#d6d3d1;border:1px solid #d6d3d1;border-radius:12px;overflow:hidden;margin:40px 0}.summary div{background:white;padding:20px;display:grid;gap:8px}.summary small,dt,figcaption{color:#78716c}.good{color:#047857}.bad,.failed{color:#b91c1c}section{margin-top:40px}h2{font-size:20px}dl{display:grid;grid-template-columns:180px 1fr;background:white;border:1px solid #e7e5e4;border-radius:12px;padding:10px 20px}dt,dd{padding:10px;margin:0;border-bottom:1px solid #f5f5f4}.table{overflow:auto;background:white;border:1px solid #e7e5e4;border-radius:12px}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;padding:13px;border-bottom:1px solid #f5f5f4}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:9px;background:#059669}.dot.failed{background:#dc2626}.visuals{display:grid;gap:18px}.visual{background:white;border:1px solid #e7e5e4;border-radius:12px;overflow:hidden}.visual.failed{border-color:#fca5a5}.visual header{display:flex;justify-content:space-between;padding:14px 18px;border-bottom:1px solid #e7e5e4}.shots{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:#e7e5e4}.shots figure{margin:0;background:white}.shots img{display:block;width:100%;height:auto}.shots figcaption{padding:10px 14px;font-size:12px}.aria-badge.passed{color:#047857}.aria-badge.warn{color:#b45309}.aria-badge.failed{color:#b91c1c}.aria-diff{margin:0 18px 14px}.aria-diff summary{cursor:pointer;font-size:13px;color:#57534e}.aria-diff pre{max-height:340px;overflow:auto;background:#fafaf9;border:1px solid #e7e5e4;border-radius:8px;padding:12px;font-size:12px;line-height:1.5}.aria-diff a{color:#1d4ed8}@media(max-width:800px){main{margin:32px auto}.summary{grid-template-columns:1fr 1fr}.shots{grid-template-columns:1fr}dl{grid-template-columns:1fr}dt{padding-bottom:0;border:0}}`;
